TICKERS = [
    {"symbol": "AAPL", "name": "Apple Inc."},
    {"symbol": "MSFT", "name": "Microsoft Corporation"},
    {"symbol": "GOOGL", "name": "Alphabet Inc."},
    {"symbol": "AMZN", "name": "Amazon.com Inc."},
    {"symbol": "NVDA", "name": "NVIDIA Corporation"},
    {"symbol": "TSLA", "name": "Tesla Inc."},
    {"symbol": "META", "name": "Meta Platforms Inc."},
    {"symbol": "BRK-B", "name": "Berkshire Hathaway Inc."},
    {"symbol": "TSM", "name": "Taiwan Semiconductor"},
    {"symbol": "V", "name": "Visa Inc."},
    {"symbol": "JPM", "name": "JPMorgan Chase & Co."},
    {"symbol": "JNJ", "name": "Johnson & Johnson"},
    {"symbol": "WMT", "name": "Walmart Inc."},
    {"symbol": "PG", "name": "Procter & Gamble Co."},
    {"symbol": "MA", "name": "Mastercard Inc."},
    {"symbol": "LLY", "name": "Eli Lilly and Company"},
    {"symbol": "HD", "name": "Home Depot Inc."},
    {"symbol": "CVX", "name": "Chevron Corporation"},
    {"symbol": "MRK", "name": "Merck & Co. Inc."},
    {"symbol": "ABBV", "name": "AbbVie Inc."},
    {"symbol": "AVGO", "name": "Broadcom Inc."},
    {"symbol": "PEP", "name": "PepsiCo Inc."},
    {"symbol": "KO", "name": "Coca-Cola Company"},
    {"symbol": "COST", "name": "Costco Wholesale Corp"},
    {"symbol": "AMD", "name": "Advanced Micro Devices"},
    {"symbol": "INTC", "name": "Intel Corporation"},
    {"symbol": "NFLX", "name": "Netflix Inc."},
    {"symbol": "DIS", "name": "Walt Disney Company"},
    {"symbol": "NKE", "name": "Nike Inc."},
    {"symbol": "SBUX", "name": "Starbucks Corporation"},
    {"symbol": "UBER", "name": "Uber Technologies"},
    {"symbol": "ABNB", "name": "Airbnb Inc."},
    {"symbol": "PLTR", "name": "Palantir Technologies"},
    {"symbol": "COIN", "name": "Coinbase Global"},
    {"symbol": "HOOD", "name": "Robinhood Markets"},
    {"symbol": "GME", "name": "GameStop Corp."},
    {"symbol": "AMC", "name": "AMC Entertainment"},
]
